vinegarhq/vinegarhq.github.io

- src/Configuration/index.md
- src/Home/faq.md
- src/Home/index.md
- src/Installation/guides/source.md
- src/Installation/index.md
> grammar fix

- src/Configuration/index.md
- src/Configuration/tips-and-tricks/index.md
- src/Home/index.md
- src/Installation/guides/source.md
> grammar fixes

- src/Configuration/tips-and-tricks/index.md
Added more information about where it should be created/located, and an example of usage.
> Add more information about the overlay folder.

- src/SUMMARY.md
- src/Troubleshooting/winehq.md
Part of https://github.com/vinegarhq/vinegar/issues/156
> Add "Reporting issues to WineHQ" page

- src/Troubleshooting/index.md
This documents the stuttering and freezing issue seen by some nvidia users, as well as potential workaround steps.
> Troubleshooting: Stuttering and freezing (Nvidia GPU)

- src/Troubleshooting/index.md
Closes https://github.com/vinegarhq/vinegar/issues/154.
> Document webcam V4L2 issue

- src/Troubleshooting/index.md
Fixes 0d1b4b786b10b2ce8624d64b18c42659dafa0f91
> Oops: Fix formatting errors with webcam v42l issue

- src/Configuration/index.md
P.S: sorry for forgetting about this wael :(
commit also caught some markdown formatting issue with another table accidentally. hope you don't mind lol
> Document gpu option in binary

- src/Troubleshooting/index.md
This PR makes significant changes to many of the issues documented in troubleshooting. Some were entirely rewritten.
It also adds documentation for some issues which are currently missing.
> The ginourmous November 2023 troubleshooting rewrite

- src/Home/index.md
List player and studio's requirements separately. List minimum Wine versions and required patches.
Also link to Roblox's official minimum requirements.
> Elaborate on Vinegar's minimum requirements

- src/Home/index.md
Made the Legal Advisory possibly better by separating it from the system requirements and making it italic.
> Made the Legal Advisory possibly better

- src/Installation/guides/source.md
Adding Section of dependencies that may be required to build vinegar, see vinegar-dev in the discord for more info
> Updated Building Dependencies

- src/Installation/guides/flatpak.md
- src/Installation/guides/package.md
- src/Installation/guides/snap.md
- src/Installation/index.md
- src/SUMMARY.md
Adds Fedora COPR and Snap, and images/badges for everything
> Sort by popularity and add badges

- src/Installation/guides/package.md
Do not use $ or # with the `sh` language. It will interpret it as a comment. Instead, use `console`.
> Shell $/# everywhere

- src/Configuration/index.md
Its a small fix, but it'll do.
> Fix Typo with Configuration wiki page

- src/Configuration/tips-and-tricks/index.md
Related to issue [#406](https://github.com/vinegarhq/vinegar/issues/406).
> Add studio backup section

- src/Troubleshooting/index.md
Added "Wine is not supported" error message in the troubleshooting page. 
Thanks for showing me how to contribute to open source!
> Updating Troubleshooting.md

- src/Sober/Configuration/index.md
- src/Sober/Troubleshooting/index.md
part of #143 because I did not realize it before it was merged
> updated outdated information (pr #143.1)

- src/Sober/Home/index.md
- src/Sober/Installation/index.md
- src/Sober/Troubleshooting/index.md
Title. Just somewhat minor changes to wording/spelling/grammar.
> Changes to wording/fixes in grammar and spelling

- src/Sober/Troubleshooting/index.md
this was somehow not caught during review in #143
(was going to make a review but social anxiety)
> fix links to soberdocs

- src/Sober/Installation/index.md
Make "tips" in the Sober installation point to the correct link.
> Fix dead link

- src/Sober/Configuration/tipsAndTricks.md
> add fullscreen + asset overlay to sober tips

- src/Troubleshooting/index.md
A fix for the limited file explorer view.
> Add fix for inaccessible Linux (home) files from explorer.

- src/Sober/FAQ/index.md
> multi instances faq
